# Generated by Django 5.0.1 on 2024-02-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_access_token_customuser_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='refresh_token',
        ),
    ]
