# Generated by Django 5.0.1 on 2024-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_onetimepassword_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='updated_at',
        ),
    ]
