version: '3.8'

services:
  web:
    image: web
    build: .
    ports:
      - 8000:8000
    command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
    depends_on:
      - redis
  redis:
    image: redis
    expose:
      - 6379
    command: redis-server --save 60 1 --loglevel warning

      