# Generated by Django 5.0.1 on 2024-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
