# Generated by Django 5.0.1 on 2024-02-10 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='attemts',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
